/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

import org.mozilla.gradle.Dependencies

buildscript {
    ext.androidx_version = '1.7.0'
    ext.architecture_components_version = '2.8.6'
    ext.kotlin_version = '2.2.10'
    ext.coroutines_version = '1.8.1'
    ext.moz_components_version = '24.0.1'
    ext.androidx_work_version = '2.9.1'
    ext.adm_version = '1.0.1'
    ext.oss_licenses_version = '17.1.0'

    ext.robolectric_version = '4.13'

    ext.test_core = '1.6.1'
    ext.test_runner = '1.6.2'
    ext.test_rules = '1.6.1'
    ext.test_orchestrator = '1.5.0'
    ext.espresso_version = '3.6.1'
    ext.uiautomator_version = '2.3.0'
    ext.junit = "1.2.1"

    repositories {
        google()
        mavenCentral()
        maven {
            url "https://maven.mozilla.org/maven2/"
        }
    }

    dependencies {
        
        
    }
}

plugins {
    id 'com.android.application' version '8.13.2' apply false
    id 'org.jetbrains.kotlin.android' version '2.2.10' apply false
    id 'org.jetbrains.kotlin.kapt' version '2.2.10' apply false
    id 'com.google.android.gms.oss-licenses-plugin' version '0.12.0' apply false
    id "io.gitlab.arturbosch.detekt" version "1.23.7"
}

detekt {
    toolVersion = "1.23.7"
    source.setFrom(files("$projectDir"))
    config.setFrom(files("$projectDir/quality/detekt.yml"))
    buildUponDefaultConfig = true
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            url "https://maven.mozilla.org/maven2/"
        }
    }
}

task clean(type: Delete) {
    delete rootProject.layout.buildDirectory
}

